os: linux
dist: bionic
language: php

services:
  - xvfb
  - mysql
  - docker

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - TESTS_DB_PASS=""
    - TESTS_DB_HOST=localhost
  jobs:
    - WP_VERSION=latest # 5.4
    - WP_VERSION="5.3"
    - WP_VERSION="5.2"
    - WP_VERSION="5.1"
    - WP_VERSION="5.0"
    - WP_VERSION=nightly

php:
  - 7.4
  - 7.3
  - 7.2

jobs:
  fast_finish: true
  allow_failures:
  - env: WP_VERSION=nightly
  exclude:
  # These WP Versions don't work on PHP 7.4
  - php: 7.4
    env: WP_VERSION="5.2"
  - php: 7.4
    env: WP_VERSION="5.1"
  - php: 7.4
    env: WP_VERSION="5.0"
  include:
  # - name: "E2E Tests"
  #   php: 7.4
  #   env: DOCKER_COMPOSE_VERSION=1.25.0 WP_VERSION=latest
  #   install:
  #     # Upgrade docker-compose.
  #     - sudo rm /usr/local/bin/docker-compose
  #     - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  #     - chmod +x docker-compose
  #     - sudo mv docker-compose /usr/local/bin
  #     # Setup and Install Node.
  #     - nvm install --lts
  #     - node -v
  #     - npm -v
  #     - npm install
  #     # Start the Environment.
  #     - composer run env up
  #     # Setup Environment.
  #     - composer run env:setup
  #   script:
  #     - npm run test
  #   after_script:
  #     - ./vendor/bin/llms-env down
  - name: "PHP Unit Test Coverage"
    php: 7.4
    env: WP_VERSION=latest RUN_CODE_COVERAGE=1
    before_script:
      # Download CodeClimate Test Reporter
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
    script:
      - ./cc-test-reporter before-build
      - composer run-script tests-run -- --coverage-clover clover.xml
    after_script:
      - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT

before_install:
  # Disable xDebug for faster builds
  - |
    if [ "1" != $RUN_CODE_COVERAGE ] && [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi
  - |
    # Raise PHP memory limit to 2048MB
    echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Install composer deps.
  - composer install

install:
  # Install Tests.
  - ./vendor/bin/llms-tests install llms_tests root '' localhost ${WP_VERSION}

script:
  # Check coding standards.
  - composer run-script check-cs-errors
  # Run phpunit tests.
  - composer run-script tests-run

notifications:
  slack: VzwXDPjuNCrKed9ACY7dwzyIjcnt6G1iC1LnKAOIx9fyPZ7TARLIf5bSa9M7P5w4uQHK7kpm5yFNtPHKGwaazZnCZxH8jcDMc4M8y3w6j9uNlbidOgfrCpp07lY6kpd8ViR7ANZ4V5Noz+ts8/gSA0yUib6vGP87s6RKHTyVTfNuFmHui7t6vF3S1VCXm4JmOrqmZbY9DlN+8JcyE0Ao3KOk/UDSCZICqo7cYnMci2oHGfb+2VRu49B61tASnV0r/dRu7gjEQTtqwElIJfuP0hGeAYc6bee5vFLA4EIdz2TMgr/Fm1El5eIg+1ZB4bOVEHzUlonLLGaUlqcYfKtmmYiV8BBnte1xBlEflLxYj92ethTUtTvkicVmtK50IlyL8kpb4WBwhXMEjSoKGLmdfaeNGKZ0vS/BnyDA0eWmt4EQ5ZVQL50ukhvmOAXhMB5T+K6Bg6T3yJzXIxej0MrSSNVygpeIwl5RqleXOKJJtJe3TsrsQfdqidXVrKAGSrwlwDRSMLC7JN3l99+5PEXzgb106TE0TBgrMOEClTVyH4gAjplqQ70diw9SAp0rnU518dTDj9HMvZ7KcGQgnAzKI82iB1LaWsWrMjqHtPbn/h+2vRDQNRnx8umnCmC8ezRr4l+xZ8Cb9KgrhvJW+bed3pQFmD/LerSuW6ZgHFsN/KI=
